### ISSUE TITLE
Change layout angle programmatically

### ISSUE THREAD

**Issue by uberspot** [rongi/rotate-layout#1]
Hey, I might have missed it somewhere but is there a way to change the contained layout angle via code instead of using the xml [app:layout_angle="90"] ? 
So that the angle changes dynamically. 

EDIT: I tried doing `((RotateLayout.LayoutParams) layout.getView().getLayoutParams()).angle = (int) newAngle;` and it worked but it doesn't seem very clean.

**Comment by Mr-Developer** [comment]
Any update on this being done programmatically yet?

**Comment by rongi** [comment]
@Mr-Developer Right now it is possible to change angle by modifying layout parameters of the child view. But I'll look into this and implement more convenient method in a week or may be earlier.

**Comment by rongi** [comment]
Implemented in version 2.0.0

To implement this it was necessary to make rotate angle xml parameter of RotateLayout, not layout parameter of it's view. Which arguable is more convenient. So now we have new major version of this view with compatibility break.
