### ISSUE TITLE
it does not work if include a webview and after the webview loadUrl.

### ISSUE THREAD

**Issue by shirensong** [rongi/rotate-layout#3]
I have a landscape activity and use below layout, and call mWebView.loadUrl("http://www.google.com");  it will cause the webview only fill the center of the screen. And if not call loadUrl, seems it is ok. Why?

![1](https://cloud.githubusercontent.com/assets/2290217/4682865/902330e6-5621-11e4-874b-59adc65bae32.png)

    <com.github.rongi.rotate_layout.layout.RotateLayout xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/form1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#ff0000">

            <WebView
                android:id="@+id/webview"
                app:layout_angle="90"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

    </com.github.rongi.rotate_layout.layout.RotateLayout>

**Comment by rongi** [comment]
Looks like WebView bug to me.

**Comment by wiliams-xu** [comment]
yep, I got the same problem.
