### ISSUE TITLE
"error: Error parsing XML: unbound prefix" and "Attribute is missing the Android namespace prefix"

### ISSUE THREAD

**Issue by admiralchip** [rongi/rotate-layout#6]
Hello,

I'm using this library to achieve a horizontal list view by implementing the suggestion given by Kc Ochibili as an answer to this question: [http://stackoverflow.com/questions/3240331/horizontal-listview-in-android](http://stackoverflow.com/questions/3240331/horizontal-listview-in-android). I'm getting the following errors when I try to use the library:

"error: Error parsing XML: unbound prefix"

and 

"Attribute is missing the Android namespace prefix"

Here's what the code looks like so far:

       `<com.github.rongi.rotate_layout.layout.RotateLayout
    app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context="com.example.newsfeedreader.NewsDisplay$PlaceholderFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >
    
        <TextView
            android:id="@+id/rss_feed"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:clickable="true"
            app:layout_angle="-90"
            />
     </com.github.rongi.rotate_layout.layout.RotateLayout>`

How can I get rid of these errors so that I can use this library? I'm trying to build an RSS feed reader by following this tutorial: [https://www.androidpit.com/java-guide-2-program-your-own-rss-reader](https://www.androidpit.com/java-guide-2-program-your-own-rss-reader).

P.S. I'm a newbie when it comes to android development so please bear with me. :)

**Comment by rongi** [comment]
Thank you for the report.

Use 

`xmlns:app="http://schemas.android.com/apk/res-auto"`

instead of

`app="http://schemas.android.com/apk/res-auto"`

I've updated the answer

**Comment by admiralchip** [comment]
Thanks! It cleared one of the errors. However, I get this error when I want to use `app:layout_angle="-90"` 

error: No resource identifier found for attribute 'layout_angle' in package  'net.narrowgateit.naijholicnewsfeedreader'

What could be the problem?

**Comment by rongi** [comment]
Check the README on the main page of the library https://github.com/rongi/rotate-layout

API was changed, angle now is a layout attribute, not View's attribute. Move app:angle like in the README to RotateLayout

```
<com.github.rongi.rotate_layout.layout.RotateLayout
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
**    app:angle="90"> <!-- Specify rotate angle here -->**

    <YourLayoutHere
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">
    </YourLayoutHere>
</com.github.rongi.rotate_layout.layout.RotateLayout>
```

**Comment by admiralchip** [comment]
Thanks for the reply! It cleared the error quite nicely but my layout does not rotate. Not sure where I went wrong.

Here is what I've got so far based on the corrections:

`<com.github.rongi.rotate_layout.layout.RotateLayout
    xmlns:app="http://schemas.android.com/lib/com.github.rongi.rotate_layout.layout"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:angle="-90" >
        <TextView
            android:id="@+id/rss_feed"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:clickable="true"
            />
     </com.github.rongi.rotate_layout.layout.RotateLayout>`

Is it because the above is wrapped in a Relative layout?

**Comment by rongi** [comment]
Use

`xmlns:app="http://schemas.android.com/apk/res-auto"`

instead of

`xmlns:app="http://schemas.android.com/lib/com.github.rongi.rotate_layout.layout"`

**Comment by admiralchip** [comment]
I've done that. It's still not rotating.

**Comment by rongi** [comment]
Try to build and launch example application added to this project. Is it works for you? I just copypasted your code to the project and it worked fine for me.

**Comment by admiralchip** [comment]
I tried using `xmlns:app="http://schemas.android.com/apk/res-auto` again but my app crashes. When I check the logcat I see "Starting input on non-focused client".

I'll try to launch the example application and let you know what happens.

**Comment by rongi** [comment]
I don't think this is because of my lib.

**Comment by admiralchip** [comment]
I was able to get rid of the error and was able to rotate one of the layouts I had to rotate by -90 so the container for the list items now scrolls horizonally. However, one thing I'm stuck in now is rotating the list items in my feed reader by 90 degrees so that they'll be upright. Currently they all appear sideways. I haven't been able to figure it out. I was wondering if you'd give a suggestion. My code is a slightly extended version of the AndroidPitRSS source code (I've forked it so you can find it on my github page) and I've been trying to use your library with it. I used the `setRotation()` method on items that was returned in the readRSS method but I got an error saying that I couldn't use it on a primitive type int.

Have you got any suggestions of something I can use from your library to achieve this? (Please bear with me. I'm a newbie in Android development)
