### ISSUE TITLE
Not working in case of VideoView

### ISSUE THREAD

**Issue by khawarraza** [rongi/rotate-layout#7]
I like to rotate my VideoView. I tried your library but it did not worked in this case. Any workout for this?

**Comment by rongi** [comment]
VideoView draws directly into video memory, It isn't possible to rotate it the way RotateLayout does it.

**Comment by david99999** [comment]
Hi, do you know why the views  can only be ratated in multiples of 90 degress?
I've modified this library by removing the fixAngle method to allow rotation for any angle, and indeed the view rotates its drawn content by the specified angle but the view itself is not rotated (example 45 degrees), but if I rotate in a 90 degrees it rotates view itself correctly.

I've search arounf the web and everybody says "use setrotation" or "rotation in xml...", but I'm not able to rotate a view itself by 45 degrees.

Can anyone point me in the right direction to be able to rotate a view in arbitrary angle?

Thank you very much

**Comment by rongi** [comment]
@david99999 It is possible to rotate a view by any angle. But there is a problem. Any view in Android should be inside a rectangle with the sides parallel to the sides of the screen. And determining rectangle containing another, rotated rectangle is not a trivial task. This is why I skipped implementation of rotation of non multiple of 90. But it still can be done and it isn't very challenging task.

**Comment by david99999** [comment]
Hi @rongi thank you very much for your answer, is there any way to override the onlayout por the required method to draw directly in a rotated position?

**Comment by rongi** [comment]
@david99999 Yes, it is possible, but not trivial and requires some effort.

**Comment by david99999** [comment]
@rongi thank you, can you point me in the right direction to do that?
Which method should I used?
